application: thorn-hackathon-viz
version: bq
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css/*
  static_dir: css

- url: /images/*
  static_dir: images

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: django
  version: latest
